# Generated by Django 3.2.19 on 2023-06-26 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.BooleanField(default=False)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
