from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    """
    Create the layout of the Order Form
    """

    class Meta:
        model = Order
        fields = (
            'full_name',
            'email',
            'phone_number',
            'country',
            'post_code',
            'town_or_city',
            'address_line1',
            'address_line2',
            'county_or_state',
        )
    
    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove autogenerated labels and 
        set autofocus to first form field
        """

        super().__init__(*args, **kwargs)
        placeholders = {
            'full_name': 'Full Name',
            'email': 'Email Address',
            'phone_number': 'Phone Number',
            'country': 'Country',
            'post_code': 'Postcode',
            'town_or_city': 'Town or City',
            'address_line1': 'Address Line 1',
            'address_line2': 'Address Line 2',
            'county_or_state': 'County/State',
        }

        self.fields['full_name'].widget.attrs['autofocus'] = True
        # Set an asterix on required fields, and placeholder on all fields
        for field in self.fields:
            if field != 'country':
                if self.fields[field].required:
                    placeholder = f'{placeholders[field]} *'
                else:
                    placeholder = placeholders[field]
                self.fields[field].widget.attrs['placeholder'] = placeholder
                self.fields[field].widget.attrs['class'] = 'stripe-style-input'
                self.fields[field].label = False